# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6a567091076a4f49692210d9e60aaedc73a88c1507d65cd8b95243d535d6f409f60759eef0da6a7167f89ec5932accb4ba4b9514d176717db79630bebe4ed1a

test:
  secret_key_base: 3f25458840a71860bf1265d15acca29c93ea1e67af9e91beac49fa4657ac8cc689042efe6058c2b13fcea14822fbbc19ddad2b0e9806a376779f4eebf8d320a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
